### ISSUE TITLE
全ページ（Resion, assignment & worktime etc.）へアクセス不能

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#10]

**Comment by heromiya** [comment]
The server has been disconnected due to problems caused by electricity interruptions. Now it recovered all functions.

**Comment by kimijimasatomi** [comment]
宮崎様、

ご調整ありがとうございます。
以下のページを確認致しました。
http://guam.csis.u-tokyo.ac.jp/dawei/assignments.php
Finished, Approvedが各１００と表示されております。
把握しているだけでもDaweiでapprovedしたものが約1,200と記憶しております。
これら画像がどこに行ったかお分かりになりますか？

どうぞよろしくお願い致します。

 君嶋里美

Date: Sat, 11 Oct 2014 00:03:22 -0700

**Comment by heromiya** [comment]
fixed it. Please check it. http://guam.csis.u-tokyo.ac.jp/dawei/assignments.php
For better performance of displaying the table, the records are shown by 100 records. Please change pages by the links "prev" and "next" in the top bar.

**Comment by kimijimasatomi** [comment]
ご調整ありがとうございました。
