### ISSUE TITLE
区画のシェイプファイル＿ラオス

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#11]
以前にもお願いしたのですが、ラオスの区画シェイプファイルをお送り頂ければ幸いです。

**Comment by heromiya** [comment]
Please download it from http://guam.csis.u-tokyo.ac.jp/dawei/dawei_target.zip
The Shapefile also includes target extents for Dawei. You may filter them by GIS software. If you need Shapefile only with the extents for Laos, please let me know.

**Comment by kimijimasatomi** [comment]
m鍋、

ありがとうございました。

埴訐鐫

Date: Sat, 11 Oct 2014 00:12:42 -0700
