### ISSUE TITLE
地域別のフィルターの追加のお願い

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#12]
地域別のフィルターの追加をお願いしたい場合、どのくらいお時間が掛かるでしょうか？

**Comment by heromiya** [comment]
Done it. Please check http://guam.csis.u-tokyo.ac.jp/dawei/assignments.php . Also added a function to limit the records shown to 100.

**Comment by kimijimasatomi** [comment]
以下の様な地域ID別のフィルターの追加は可能でしょうか？
”6472-3679”

**Comment by heromiya** [comment]
done it http://guam.csis.u-tokyo.ac.jp/dawei/assignments.php

**Comment by kimijimasatomi** [comment]
ご調整ありがとうございました。
