### ISSUE TITLE
アクセス不可

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#14]
インターフェースにアクセスできません。
以下の表示がでます。
”There is an error with connection to the database. Please contact with administrator”.
ご調整頂ければ幸いです。

**Comment by kimijimasatomi** [comment]
表示が以下の様に変わりました。
![screen shot 0026-10-15 at 16 11 11](https://cloud.githubusercontent.com/assets/8002848/4643024/4fc7d1be-544b-11e4-9c25-461f553ec546.png)

**Comment by heromiya** [comment]
どうもありがとうございます。しばらくお待ちください。
On 2014/10/15 17:12, kimijimasatomi wrote:

> 表示が変わりました。
> screen shot 0026-10-15 at 16 11 11 https://cloud.githubusercontent.com/assets/8002848/4643024/4fc7d1be-544b-11e4-9c25-461f553ec546.png
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/heromiya/viworks/issues/14#issuecomment-59178039.

## 

Hiroyuki Miyazaki, Ph.D. 宮崎浩之 http://heromiya.net Tel:+63-947-695-3205 Skype: heromiya

**Comment by kimijimasatomi** [comment]
ご調整、よろしくお願い致します。

**Comment by kimijimasatomi** [comment]
度々申し訳ありません。復旧にどれくらいお時間がかかるでしょうか？ご連絡頂けますと幸いです。どうぞよろしくお願い致します。

**Comment by heromiya** [comment]
こちらから操作ができなくなりました。現地にて再起動を要請中です。しばらくお待ちください。

**Comment by kimijimasatomi** [comment]
よろしくお願い致します。アップデートがございましたら随時ご連絡頂ければ幸いです。

**Comment by kimijimasatomi** [comment]
ただ今アクセスできました。ご調整、ありがとうございました。
