### ISSUE TITLE
Achievement Link

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#15]
以下リンク内の”Finished”が機能致しません。
また、同リンク表示までの時間が非常に掛かります。
"Next"の表示も非常に時間がかかります。

http://guam.csis.u-tokyo.ac.jp/dawei/assignments.php

ご調整頂ければ幸いです。

**Comment by kimijimasatomi** [comment]
以下のリンクにアクセスできません。

http://guam.csis.u-tokyo.ac.jp/dawei/assignments.php
http://guam.csis.u-tokyo.ac.jp/dawei/achievements.php

"Finished”が機能致しません。

ご調整頂ければ幸いです。よろしくお願いします。

**Comment by kimijimasatomi** [comment]
上記リンクにアクセスできましたが、時間が掛かる様です。
Achievement Link：２分
Assignment Link:　３０秒

"Finished”が機能致しません。

ご調整頂ければ幸いです。よろしくお願い致します。

**Comment by kimijimasatomi** [comment]
何かアップデートがございましたら、ご連絡頂ければ幸いです。

**Comment by heromiya** [comment]
Made the Assignment list showing 50 records from 100 records to reduece load for rendering table. Please wait for modifying the Achievement list as well and fixing "Finished" buttton.

**Comment by heromiya** [comment]
- Made it also for the Achievement list.
- Fixed the "Finished" filter in the Assignments list.

**Comment by kimijimasatomi** [comment]
お手数をお掛け致しました。
ありがとうございました。
