### ISSUE TITLE
Finished/Approved

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#16]
Finished(2213)/Approved(2145)の差が６８あります。
Prev/Next機能を使い、１〜２２まで確認致しましたが、Approve もれはありませんでした。
上記の６８画像は、どこにあるかお分かりになりますか？

**Comment by kimijimasatomi** [comment]
この件に関し、ご返信頂ければ幸いです。よろしくお願い致します。

**Comment by kimijimasatomi** [comment]
何かアップデートがございましたら、ご連絡頂ければ幸いです。

**Comment by kimijimasatomi** [comment]
何かアップデートがございましたら、ご連絡頂ければ幸いです。

**Comment by kimijimasatomi** [comment]
何かアップデートがございましたら、ご連絡頂ければ幸いです。

**Comment by heromiya** [comment]
Fixed it. Number of "approved" is more than number of "Finished" because there are 3 regions approved without being marked as "Finished".

**Comment by kimijimasatomi** [comment]
お手数をお掛け致しました。
ありがとうございました。
