### ISSUE TITLE
Raster size in Pixcel

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#17]
これまでの都市部の分析に関しまして、”Raster size in Pixcel”はどのように設定されておられますか？
アドバイス頂ければ幸いです。

![screen shot 0026-10-19 at 3 06 58](https://cloud.githubusercontent.com/assets/8002848/4691023/e550b87c-5702-11e4-8df7-2a4fe5de06ce.png)

**Comment by heromiya** [comment]
用途に依ります。なお、dawei_targetはLandsat目視判読の対象タイルです。目視判読のデータでしたら、判読元の衛星画像データの解像度（ASTER:
15 m; Landsat 30 m）に合せるのが適切かと思います。

Hiroyuki Miyazaki, Ph.D. / 宮崎浩之 http://heromiya.net Tel:+63-947-695-3205

**Comment by kimijimasatomi** [comment]
アドバイス、ありがとうございます。
