### ISSUE TITLE
Slow down of the interface

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#19]
インターフェースが非常に遅いです。
ご調整頂ければ幸いです。

**Comment by heromiya** [comment]
I changed a configuration of the server so that response of the WebGIS gets better. Please access it again.

**Comment by kimijimasatomi** [comment]
The interface is still slow. Are there any alternative ways to make it faster?

**Comment by heromiya** [comment]
Sorry for late response. Server response of loading Landsat imagery has been improved. Please check it.
