### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#22]
The following message  has been shown in the interface.
Please kindly fix it.

"There is an error with connection to the database. Please contact with administrator."

**Comment by heromiya** [comment]
Fixed the problem. Please try to access it again.
On 2015/02/21 10:31, kimijimasatomi wrote:

> The following message has been shown in the interface.
> Please kindly fix it.
> 
> "There is an error with connection to the database. Please contact with administrator."
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/heromiya/viworks/issues/22.

## 

Hiroyuki Miyazaki, Ph.D. 宮崎浩之 http://heromiya.net Tel:+63-947-695-3205 Skype: heromiya

**Comment by kimijimasatomi** [comment]
thank you very much.
