### ISSUE TITLE
Request of checking working hour

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#23]
Could you please check whether working hour has been counted properly or not?

**Comment by kimijimasatomi** [comment]
For example, I approved some images worked by three students (nothing to be digitized); thought, nothing has not been reflected.

**Comment by heromiya** [comment]
I restored the functions. Working hour is calculated once a day at 5am JST. Please check again later.

Miyazaki

On 2015/02/21 12:13, kimijimasatomi wrote:

> For example, I approved some images worked by three students (nothing to be digitized); thought, nothing has not been reflected.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/heromiya/viworks/issues/23#issuecomment-75354868.

## 

Hiroyuki Miyazaki, Ph.D. 宮崎浩之 http://heromiya.net Tel:+63-947-695-3205 Skype: heromiya

**Comment by kimijimasatomi** [comment]
thank you very much.
