### ISSUE TITLE
Error_effective time, # of features, average SV of drawing time

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#24]
Effective time, # of features, average SV of drawing time etc have not been shown.
Also  working time has not been shown below.
http://guam.csis.u-tokyo.ac.jp/dawei/worktime.stats.php

![screen shot 0027-02-27 at 21 34 26](https://cloud.githubusercontent.com/assets/8002848/6414556/e966f77a-beca-11e4-86c4-98cf354b97db.png)

Please kindly check out the system.
Thank you very much.

**Comment by kimijimasatomi** [comment]
Are there any problems in the system regarding this issue?

**Comment by heromiya** [comment]
I'm sorry for late response. I found a problem in the system and fixed it. Please check it.
