### ISSUE TITLE
Interface is not available

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#25]
![screen shot 0027-02-28 at 11 27 22](https://cloud.githubusercontent.com/assets/8002848/6424852/f3d12dd0-bf3c-11e4-84e0-11d773e46b9e.png)

Please kindly check out the system.
Thank you very much.

**Comment by heromiya** [comment]
It seems problem within CSIS as http://www.csis.u-tokyo.ac.jp is also down. Please wait for a while.

**Comment by kimijimasatomi** [comment]
Thank you very much.

**Comment by heromiya** [comment]
Connection to the server has been restored right now.

**Comment by kimijimasatomi** [comment]
Thank you for your kind info.
