### ISSUE TITLE
LMエラー

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#7]
位置情報がずれております。

**Comment by heromiya** [comment]
Please specify the Landsat imagery by granule ID, e.g. LM11400501972356AAA04.

**Comment by kimijimasatomi** [comment]
LM11360481972352AAA04とLM21360481975363GDS03です。

**Comment by heromiya** [comment]
両者とも元のデータの位置がずれています。GCPによる精密幾何補正が必要です。

**Comment by kimijimasatomi** [comment]
ありがとうございます。
承知致しました。
