### ISSUE TITLE
Functionボタンエラー

### ISSUE THREAD

**Issue by kimijimasatomi** [heromiya/viworks#9]
結構な割合で"Function"ボタンが出てきません。

**Comment by kimijimasatomi** [comment]
![screen shot 0026-10-16 at 11 40 46](https://cloud.githubusercontent.com/assets/8002848/4657679/bd762de8-54ee-11e4-8c70-16e331d15505.png)

**Comment by heromiya** [comment]
Fixed it to be stable.
- Changed dojo library resource from ajax.googleapis.com to local.

**Comment by kimijimasatomi** [comment]
ありがとうございました。
